---
- name: Override default data with user one
  set_fact:
    updated_trust: "{{ updated_trust | default([]) + [ ssh_trust_defaults[0] | combine(item, recursive=True) ] }}"
  with_items: "{{ ssh_trust }}"
  tags:
    - always

- name: Show target ssh_trust variable
  debug:
    var: updated_trust
    verbosity: 1

- name: Explicitly set trust variable to operate over
  set_fact:
    ssh_trust: "{{ updated_trust }}"
  tags:
    - always

- include_tasks: master.yml
  with_items: "{{ ssh_trust }}"
  loop_control:
    loop_var: ssh_trust_config
  when: ssh_trust_config.master is defined and ssh_trust_config.master
  tags:
    - master

- include_tasks: slave.yml
  with_items: "{{ ssh_trust }}"
  loop_control:
    loop_var: ssh_trust_config
  when: ssh_trust_config.master is defined and not ssh_trust_config.master
  tags:
    - slave

- include_tasks: fingerprints.yml
  with_items: "{{ ssh_trust }}"
  loop_control:
    loop_var: ssh_trust_config
  when: ssh_trust_config.master is defined and ssh_trust_config.master
  tags:
    - master
