---
- name: Ensure trust user for slave host
  become: yes
  become_user: root
  user:
    name: "{{ ssh_trust_config.trust_user.name }}"
    comment: "{{ ssh_trust_config.trust_user.comment | default('') }}"
    createhome: yes
    state: "{{ ssh_trust_config.trust_user.state | default('present') }}"
    shell: "{{ ssh_trust_config.trust_user.shell | default('/bin/false') }}"
  when: ssh_trust_config.trust_user.create

- name: Include finding master hosts tasks
  include_tasks: find_masters.yml
  loop: "{{ ansible_play_hosts_all }}"
  loop_control:
    loop_var: host

- name: Show resulted master hosts list
  debug:
    var: master_hosts
    verbosity: 1

- name: Fail in case there is no masters for given group
  fail:
    msg: "We found SSH trust group name '{{ ssh_trust_config.group }}' for slave host '{{ inventory_hostname }}'. But seems that there is no masters with such a group, so we gracefully stop the playbook. Check your vars and re-run, please."
  when: master_hosts == []

- name: Ensure master public key for trust user
  become: yes
  become_user: root
  authorized_key:
    user: "{{ ssh_trust_config.trust_user.name }}"
    state: present
    key: "{{ hostvars[master_host].ssh_master_public_key.content | b64decode }}"
  loop: "{{ master_hosts }}"
  loop_control:
    loop_var: master_host
